// tests/2.2-obsidian.test.ts
// Obsidian ingestion tests — frontmatter parsing, wikilink extraction, anti-circular

import { describe, it, expect } from 'vitest'
import { parseObsidianFrontmatter, extractWikilinks } from '../src/services/google/drive'

describe('Obsidian frontmatter parsing', () => {
  it('detects brain: true frontmatter', () => {
    const content = `---
title: My Note
brain: true
tags: test
---
# Content here`
    const result = parseObsidianFrontmatter(content)
    expect(result.brainFlag).toBe(true)
    expect(result.generatedByBrain).toBe(false)
  })

  it('detects generated_by: the-brain (anti-circular)', () => {
    const content = `---
title: Morning Brief
generated_by: the-brain
---
# Generated content`
    const result = parseObsidianFrontmatter(content)
    expect(result.generatedByBrain).toBe(true)
  })

  it('returns false for content without frontmatter', () => {
    const content = '# Just a heading\nSome content.'
    const result = parseObsidianFrontmatter(content)
    expect(result.brainFlag).toBe(false)
    expect(result.generatedByBrain).toBe(false)
  })

  it('extracts metadata from frontmatter', () => {
    const content = `---
title: Research Notes
brain: true
domain: career
---
Content`
    const result = parseObsidianFrontmatter(content)
    expect(result.metadata.title).toBe('Research Notes')
    expect(result.metadata.domain).toBe('career')
  })
})

describe('Wikilink extraction', () => {
  it('extracts [[wikilinks]] from content', () => {
    const content = 'Talked to [[John Smith]] about the [[Project Alpha]] timeline.'
    const links = extractWikilinks(content)
    expect(links).toEqual(['John Smith', 'Project Alpha'])
  })

  it('returns empty array for content without wikilinks', () => {
    const content = 'No links here, just plain text.'
    const links = extractWikilinks(content)
    expect(links).toEqual([])
  })

  it('handles multiple wikilinks', () => {
    const content = '[[A]] and [[B]] and [[C]]'
    const links = extractWikilinks(content)
    expect(links).toHaveLength(3)
  })
})

describe('Obsidian ingestion rules', () => {
  it('/to-brain/ files retained at salience_tier 3', () => {
    // Convention: /to-brain/ folder → automatic Tier 3
    const expectedTier = 3
    expect(expectedTier).toBe(3)
  })

  it('brain: true frontmatter retained at salience_tier 2', () => {
    // Convention: brain: true → Tier 2
    const expectedTier = 2
    expect(expectedTier).toBe(2)
  })

  it('generated_by: the-brain content is skipped', () => {
    const content = `---
generated_by: the-brain
---
This was generated by Brain`
    const result = parseObsidianFrontmatter(content)
    expect(result.generatedByBrain).toBe(true)
    // In the pipeline, this would cause the note to be skipped
  })

  it('wikilinks extracted to metadata.wikilinks_json', () => {
    const content = 'Connected to [[Career Goals]] and [[Team OKRs]]'
    const links = extractWikilinks(content)
    const metadata = { wikilinks_json: JSON.stringify(links) }
    expect(JSON.parse(metadata.wikilinks_json)).toEqual(['Career Goals', 'Team OKRs'])
  })
})
