/* eslint-disable */
// Generated by Wrangler by running `wrangler types src/types/cloudflare-env.generated.d.ts --include-runtime false` (hash: e0cfecbae027ca9d808e6456ff9ebdeb)
interface __BaseEnv_Env {
	KV_SESSION: KVNamespace;
	R2_ARTIFACTS: R2Bucket;
	R2_OBSERVABILITY: R2Bucket;
	D1_US: D1Database;
	D1_EU: D1Database;
	VECTORIZE: VectorizeIndex;
	HYPERDRIVE_CANONICAL: Hyperdrive;
	ANALYTICS: AnalyticsEngineDataset;
	QUEUE_HIGH: Queue;
	QUEUE_NORMAL: Queue;
	QUEUE_BULK: Queue;
	QUEUE_DEAD: Queue;
	QUEUE_ACTIONS: Queue;
	BROWSER: Fetcher;
	AI: Ai;
	TELEGRAM_BOT_USERNAME: "haetsal_os_bot";
	WORKER_DOMAIN: "haetsalos.specialdarksystems.com";
	TELNYX_FROM_NUMBER: "+13236785761";
	AI_GATEWAY_ID: "haetsal-brain-gateway";
	AI_GATEWAY_ACCOUNT_ID: "d3f0a1c579945862edc9c6f6e36e448a";
	HINDSIGHT_DEDICATED_WORKERS_ENABLED: "false";
	HINDSIGHT_DEDICATED_WORKER_COUNT: "2";
	GRAPHITI_RUNTIME_MODE: "container";
	MCPAGENT: DurableObjectNamespace<import("../workers/mcpagent/index").McpAgentDO>;
	HINDSIGHT: DurableObjectNamespace<import("../workers/mcpagent/index").HindsightContainer>;
	HINDSIGHT_WORKER: DurableObjectNamespace<import("../workers/mcpagent/index").HindsightWorkerContainer>;
	GRAPHITI: DurableObjectNamespace<import("../workers/mcpagent/index").GraphitiContainer>;
	BOOTSTRAP_WORKFLOW: Workflow<Parameters<import("../workers/mcpagent/index").BootstrapWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../workers/mcpagent/index");
		durableNamespaces: "McpAgentDO" | "HindsightContainer" | "HindsightWorkerContainer" | "GraphitiContainer";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TELEGRAM_BOT_USERNAME" | "WORKER_DOMAIN" | "TELNYX_FROM_NUMBER" | "AI_GATEWAY_ID" | "AI_GATEWAY_ACCOUNT_ID" | "HINDSIGHT_DEDICATED_WORKERS_ENABLED" | "HINDSIGHT_DEDICATED_WORKER_COUNT" | "GRAPHITI_RUNTIME_MODE">> {}
}
