/* eslint-disable */
// Generated by Wrangler by running `wrangler types src/types/cloudflare-env.generated.d.ts --include-runtime false` (hash: b5efeefb7fde15f8ffa00c33af772c52)
interface __BaseEnv_Env {
	KV_SESSION: KVNamespace;
	R2_ARTIFACTS: R2Bucket;
	R2_OBSERVABILITY: R2Bucket;
	D1_US: D1Database;
	D1_EU: D1Database;
	HYPERDRIVE_CANONICAL: Hyperdrive;
	ANALYTICS: AnalyticsEngineDataset;
	QUEUE_HIGH: Queue;
	QUEUE_NORMAL: Queue;
	QUEUE_BULK: Queue;
	QUEUE_DEAD: Queue;
	QUEUE_ACTIONS: Queue;
	BROWSER: Fetcher;
	AI: Ai;
	ASSETS: Fetcher;
	TELEGRAM_BOT_USERNAME: "haetsal_os_bot";
	WORKER_DOMAIN: "haetsalos.specialdarksystems.com";
	TELNYX_FROM_NUMBER: "+13236785761";
	NEON_CONNECTION_STRING: string;
	CANONICAL_POSTGRES_CONNECTION_STRING: string;
	AI_GATEWAY_ID: string;
	AI_GATEWAY_ACCOUNT_ID: string;
	AI_GATEWAY_TOKEN: string;
	SENDBLUE_API_KEY_ID: string;
	SENDBLUE_API_SECRET_KEY: string;
	SENDBLUE_PHONE_NUMBER: string;
	SENDBLUE_WEBHOOK_PATH_SECRET: string;
	SENDBLUE_WEBHOOK_SIGNING_SECRET: string;
	MCPAGENT: DurableObjectNamespace<import("../workers/mcpagent/index").McpAgentDO>;
	BOOTSTRAP_WORKFLOW: Workflow<Parameters<import("../workers/mcpagent/index").BootstrapWorkflow['run']>[0]['payload']>;
	DREAM_WORKFLOW: Workflow<Parameters<import("../workers/mcpagent/index").DreamCycleWorkflow['run']>[0]['payload']>;
	ACTION_APPROVAL_WORKFLOW: Workflow<Parameters<import("../workers/mcpagent/index").ActionApprovalWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../workers/mcpagent/index");
		durableNamespaces: "McpAgentDO";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TELEGRAM_BOT_USERNAME" | "WORKER_DOMAIN" | "TELNYX_FROM_NUMBER" | "NEON_CONNECTION_STRING" | "CANONICAL_POSTGRES_CONNECTION_STRING" | "AI_GATEWAY_ID" | "AI_GATEWAY_ACCOUNT_ID" | "AI_GATEWAY_TOKEN" | "SENDBLUE_API_KEY_ID" | "SENDBLUE_API_SECRET_KEY" | "SENDBLUE_PHONE_NUMBER" | "SENDBLUE_WEBHOOK_PATH_SECRET" | "SENDBLUE_WEBHOOK_SIGNING_SECRET">> {}
}
